name: C/C++ CI OpenDIS & Examples

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Premake5
      run: bash install_premake5.sh
    - name: Create Makefiles
      run: ~/premake5 gmake
    - name: Install SDL
      run: bash install_SDL.sh
    - name: make
      run: make OpenDIS config=release